### ISSUE TITLE
Cheaper parts for slots

### ISSUE THREAD

**Issue by vogelfreiheit** [sanni/cartreader#12]
I believe this is suitable for N64, for example:
https://www.ebay.com/itm/131137330390

Much cheaper than Aliexpress lots... could this be confirmed and additional alternatives listed?

**Comment by vogelfreiheit** [comment]
Anyone?

**Comment by sanni** [comment]
I have added the slot to the parts list. Just be sure to use the 3d printed sleeve for the N64 slot to help align the cartridge perfectly since the slot in the ebay link is 2.54mm while the original N64 one is 2.5mm. But since the outer pins are just GND anyway this does not matter as long as the cartridge is inserted dead center.
