### ISSUE TITLE
Can't find Gerber files for Main PCB

### ISSUE THREAD

**Issue by Ailuros** [sanni/cartreader#15]
I downloaded the gerber files once for the main pcb from this repo, but now the "pcb" folder has moved from the root of the repo to "extras" and it no longer seems to contain the files for having the main pcb made. Have they been removed? Did you change them?

**Comment by sanni** [comment]
There will be a new pcb version coming out soon.
However if you want to build the old version you can still get the gerber files here: https://github.com/sanni/cartreader/tree/09d122369fb5bbec1bffa3a6568dc0b8f87921db/pcb

Build guide old version: https://github.com/sanni/cartreader/wiki/PCB-Build-guide
Build guide new version: https://github.com/sanni/cartreader/wiki/How-to-build-the-PCB

The gerber files for the new version are not available yet because I have not received the PCB back from China so I don't know if I maybe made a mistake.
