### ISSUE TITLE
Flashrom Progammer : Can't flash + Menu error 255

### ISSUE THREAD

**Issue by Slyazku** [sanni/cartreader#777]
When using the flashrom PCB adapter with a 29L3211 inside, plugged into the SNES port, I've got no result.
Blanckcheck, reading, etc takes 0sec and dumped files are blank.
When the first operation is complete, and after "Press Button..." prompt, I've got a 
"MenuError 
Mode = 255
Press BUtton..."
Then to the tiel screen.

Did someone managed to flash a flashchip with 12.4 HW5 ?

Thanks !

**Comment by sanni** [comment]
There was an error in the menu resulting in the flash ID function being skipped. Fixed now.

Also since there are currently no HW4/5 flash adapters you have to modify the HW3 adapter:
- cut the trace going to SNES CPU Clock and rewire Flashrom OE to SNES CS
- cut the trace going to SNES IRQ and rewire Flashrom WE to SNES WR

(you need to scratch away the solder mask of the edge connector pins to expose the copper to solder to)

![flashadapterhw5](https://user-images.githubusercontent.com/19169494/233331256-3df5bf89-e27d-459d-a9a0-66ffc0c9d6cc.jpg)
![IMG_2301](https://user-images.githubusercontent.com/19169494/233331265-7cd45f8b-efcd-4b0a-b958-19cb031c29db.JPG)
![IMG_2302](https://user-images.githubusercontent.com/19169494/233331268-2515b94e-36c3-434f-a24f-5d3a1feef74c.JPG)

**Comment by sanni** [comment]
You can update to the current github code like explained here: https://github.com/sanni/cartreader/wiki/Troubleshooting#updating-to-the-latest-github-code

**Comment by Slyazku** [comment]
Thanks !
I may be late but did you plan to make the eeprom  section appear again in the wiki, since the menu is able to do it ?

**Comment by sanni** [comment]
You can always enable the eprom menu option by setting #define enable_FLASH16 in [config.h line 108](https://github.com/sanni/cartreader/blob/master/Cart_Reader/Config.h#L108)

I have updated the [M27C322 wiki entry](https://github.com/sanni/cartreader/wiki/M27C322-Adapter) with the notion that it doesn't work, just so people don't order it and get disappointed.
